#!/bin/bash

# Function to get local IP address
get_local_ip() {
    # This works on most Unix-like systems including macOS and Linux
    ip=$(ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1' | head -n 1)
    echo $ip
}

# Get the local IP address
LOCAL_IP=$(get_local_ip)
LOCAL_IP="localhost"

# Create backend .env file
cat > backend/.env << EOL
# Auto-generated by startup script
LOCAL_IP=$LOCAL_IP
PORT=3000
FRONTEND_URL=http://$LOCAL_IP:3001
EOL

# Create frontend .env file
cat > frontend/.env << EOL
# Auto-generated by startup script
LOCAL_IP=$LOCAL_IP
PORT=3001
BACKEND_URL=http://$LOCAL_IP:3000
EOL

echo "Environment configurations saved to .env files"
echo "Backend .env:"
cat backend/.env
echo ""
echo "Frontend .env:"
cat frontend/.env

# Start backend and frontend in parallel
(
    echo "Starting backend server..."
    echo $(pwd)
    cd backend
    npm run dev -- -p 3000
) &

(
    echo "Starting frontend server..."
    echo $(pwd)
    cd frontend
    npm run dev -- -p 3001
) &

# Wait for both processes
wait

echo "Both servers have been stopped."